#
#    ,---.     ,--.                                         ,--. ,-----.,--.               ,--.
#   /  O  \  ,-|  |,--.  ,--.,--,--.,--,--,  ,---. ,---.  ,-|  |'  .--./|  ,---.  ,--,--.,-'  '-.
#  |  .-.  |' .-. | \  `'  /' ,-.  ||      \| .--'| .-. :' .-. ||  |    |  .-.  |' ,-.  |'-.  .-'
#  |  | |  |\ `-' |  \    / \ '-'  ||  ||  |\ `--.\   --.\ `-' |'  '--'\|  | |  |\ '-'  |  |  |
#  `--' `--' `---'    `--'   `--`--'`--''--' `---' `----' `---'  `-----'`--' `--' `--`--'  `--'
#
#  AdvancedChat - An advanced bukkit chat plugin.
#      GitHub (Source Code): https://github.com/sammwyy/AdvancedChat

# General plugin settings.
settings:
  # The default language to use when no suitable language is found.
  # It is also the one that will be used in the console.
  default-lang: "en"

# Automatic moderation based on chat.
automod:
  block-repeated-messages:
    enabled: true
    bypass: "chat.bypass.repeated-messages"
  block-links:
    enabled: true
    bypass: "chat.bypass.links"
    whitelist:
      - https://github.com/sammwyy/AdvancedChat
      - https://google.com

# The lines that will be cleaned in the chat when using the /chat clear command.
clear:
  lines: 20
  # Players with this permission will not have their chat cleared unless they use /chat clear all.
  bypass: "chat.bypass.clear"

# Enables a cooldown between messages from the same player.
cooldown:
  enabled: true
  # The time in milliseconds that the player must wait before being able to send another message.
  time: 1000
  # Permission to bypass the cooldown.
  bypass: "chat.bypass.cooldown"

# The format that will be used to display player messages.
#
# You can use variables from placeholderapi (https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders)
#
# You can also use internal plugin placeholders, for example: {display_name}, {name} and {message}
#
# Also you can display player profile in chat using <profile>text</profile> and when
# the cursor passes over the selected text, the profile will be displayed in the format you configure.
#
# Leave empty to disable chat formatting.
format: "%vault_prefix%<profile>{display_name}</profile>&8: &7{message}"
# The format of the messages but in the console (Leaving it empty will disable logging)
format-console: "%vault_prefix%{display_name}&8: &7{message}"

grammar:
  # Add a period (.) at the end of the messages if it does not end with one.
  append-pediod: true
  # Replaces the first character of the message with the same uppercase character.
  capitalize: true
  # Remove capital letters from messages.
  remove-caps: true

# Player profile.
profile:
  # You can execute or suggest a command to the player who clicks the name of another player in the chat.
  # COPY_TO_CLIPBOARD     Copies a text to the user's clipboard
  # OPEN_URL              Open a link with the user's browser (The user must confirm whether or not to open the link)
  # RUN_COMMAND           Run a command as the player (you can also run commands in a proxy)
  # SUGGEST_COMMAND       Suggest a command (type it in the chat but without sending)
  click:
    type: "SUGGEST_COMMAND"
    action: "/msg {clicked_player} "
  # This message is intended to appear when the cursor hovers over a player's name in chat.
  # This can be retrieved from any other plugin (and translated into the player's language)
  # using the PlaceholderAPI variable: %advancedchat_profile%
  hover: |-
    %vault_prefix%%player_name%
    &8%player_uuid%
    &r
    {i18n:profile}
    &r

# You can deactivate the chat whenever you like and nobody will be able to send messages.
restrinction:
  enabled: false
  # You can also configure a permission that will work as a bypass.
  bypass: "chat.bypass.restrinction"
